version: "3.8"

services:
  db:
    image: task-management-db
    build:
      context: .
      dockerfile: dockerfile.db
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql

  be:
    image: task-management-be
    build:
      context: .
      dockerfile: dockerfile.be
    depends_on:
      - db
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - ./:/app
volumes:
  db:
